version: ' 3 '

services:
    nginx:
        build: ./requirements/nginx
        container_name: nginx
        ports:
         - "443:443"
        volumes:
         - wordpress_files:/var/www/html
        networks:
         - my_network